
package com.cm;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SyncChannels", targetNamespace = "http://cm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SyncChannels {


    /**
     * 
     * @param type
     * @param channelinfoList
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncchannel", targetNamespace = "http://cm.com/", className = "com.cm.Syncchannel")
    @ResponseWrapper(localName = "syncchannelResponse", targetNamespace = "http://cm.com/", className = "com.cm.SyncchannelResponse")
    @Action(input = "http://cm.com/SyncChannels/syncchannelRequest", output = "http://cm.com/SyncChannels/syncchannelResponse")
    public Integer syncchannel(
        @WebParam(name = "type", targetNamespace = "")
        int type,
        @WebParam(name = "channelinfoList", targetNamespace = "")
        List<ChannelInfo> channelinfoList);

}
